### ISSUE TITLE
Add What is an OS to Background

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#108]
**Is your feature request related to a problem? Please describe.**
We never really explain what an operating system is. We should go through the basics of what an OS is and what it provides.

**Describe the solution you'd like**
A chapter in the background section describing what the an OS does exactly.

**Describe alternatives you've considered**
We could leave this out, but as people who may've only understood programming through an IDE, it might be useful to tell them how programs are originally envisioned.

**Additional context**
N/A

**Comment by angrave** [comment]
And also talk about POSIX standard (and why it exists for portability). i.e. that OSX, Linux + others implement a set of well defined POSIX system calls

By the way, the POSIX standard for how to fork (with open file descriptors) is important.
