### ISSUE TITLE
Create a Signal Creation to Delivery Diagram

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#123]
**Is your feature request related to a problem? Please describe.**
There should be a picture from signal creation to delivery that details all the steps that the kernel goes through.

**Describe the solution you'd like**
Similar format diagram for that section.

**Describe alternatives you've considered**
I think it'd be clearer with a diagram.

**Additional context**
N/A

**Comment by aneeshdurg** [comment]
https://sklinuxblog.blogspot.com/2015/05/linux-signals-internals.html?m=1

This is a really nice detailed view of how signals are handled by the kernel. Might be a good resource/refresher for whoever works on this.
