### ISSUE TITLE
Wiki Build Failing Due To Branch Protection Rule

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#167]
**Describe the bug**
As of latest commit the wiki build is failing because of branch rules.

**Expected behavior**
Nice and happy build

**Comment by bhuvy2** [comment]
https://github.com/illinois-cs241/coursebook/commit/d8f7464a84c9a358d7e2f07afbe1fcfceb3b89ce

**Comment by PradyumnaShome** [comment]
Good to note. I should set it up so that a few people get emails when the build fails.

**Comment by PradyumnaShome** [comment]
Removed branch protection rules.
