### ISSUE TITLE
Incorrect macro expansion

### ISSUE THREAD

**Issue by rajdroid** [illinois-cs241/coursebook#174]
https://github.com/illinois-cs241/coursebook/blob/4205a5cfac7a5159f50391568c129ef307c72652/introc/crash_course_introduction_to_c.tex#L78

This is an incorrect expansion of the above macro. Instead of `100`, it should be `5`.

https://github.com/illinois-cs241/coursebook/blob/4205a5cfac7a5159f50391568c129ef307c72652/introc/crash_course_introduction_to_c.tex#L86

**Comment by bhuvy2** [comment]
Thanks for reporting!
