### ISSUE TITLE
Make HTML Build

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#3]
Provide a way that the files can be molded into one website.

**Comment by apache8080** [comment]
http://pandoc.org/demos.html
This will probably be useful to convert the latex into other formats. Maybe converting into markdown and using [gitbook](https://github.com/GitbookIO/gitbook) is a way to make a nice web version of the book.

**Comment by bhuvy2** [comment]
I've looked into markdown but there is information loss when we convert latex -> markdown and back.

Ideally we want to have latex -> html which preserves attributes about each element. Pandoc can do simple stuff like change latex lists. All we'll need is to go through each of the chapter folders and have a one to one mapping (i.e. this tag does this, etc etc) which shouldn't be hard for a script or two.

**Comment by bhuvy2** [comment]
Closed for now, any additional issues should be opened up as parents.
