### ISSUE TITLE
Expand on Lightweight Processes

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#42]
Right now we don't talk about lightweight processes a lot. We should really detail the fact that a thread _is_ a process with a few flags removed

**Comment by angrave** [comment]
This one is dangerous -  be _very_ careful not confuse a beginner who has only just learned what a thread and process is. First we say they are very different, then actually they are the same!? "with just a few flags removed!" Though I understand what you mean this seems like a quick recipe for confusion and frustration unless handled with extreme tact.
