### ISSUE TITLE
Building chapters individually 

### ISSUE THREAD

**Issue by aneeshdurg** [illinois-cs241/coursebook#53]
Talked to @Ram-G and he felt that chapters should be built individually to reduce compilation time for small edits and I think it's also useful as that would open the door for custom build scripts for individual chapters.
The proposal is to generate a Pdf per chapter and have the global makefile make each chapter then stitch the pdfs together.

**Comment by bhuvy2** [comment]
Most of the build time is actually spent installing texlive, we only spend 20s on the actual build which we could speed up through caching

https://travis-ci.com/illinois-cs241/coursebook/jobs/181142720#L159

We could pull a docker image to a local folder, cache the folder then we'd shave 7 minutes off the build.

**Comment by aneeshdurg** [comment]
I think he meant the local build time when testing. It's not super slow. But it is a bit confusing that each chapter can be individually generated

**Comment by bhuvy2** [comment]
Resolved

https://github.com/illinois-cs241/coursebook/blob/pdf_deploy/

To build

```
make processes/processes.pdf
```

Note, does not clean for you though.
