### ISSUE TITLE
Extra: Intro to Security

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#60]
Some topics I can think of

* Stack Smashing
* HTTP Request Spoofing/Catching
* System security with seccomp or `pledge` (I really like pledge)

**Comment by bhuvy2** [comment]
Since @redsn0w422 is security expert, what are the other topics covered in 461/63? It may be useful for a potential curriculum change coming up.

**Comment by PradyumnaShome** [comment]
Resolved through #86.
