### ISSUE TITLE
Define wait time/response time/etc

### ISSUE THREAD

**Issue by aneeshdurg** [illinois-cs241/coursebook#72]
**Is your feature request related to a problem? Please describe.**
Wait time and response time aren't actually given a definition in the scheduling page

**Describe the solution you'd like**
Just a section defining some terminology

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by aneeshdurg** [comment]
Ah, nvm it is defined, but it's defined in this paragraph of text that's not easy to parse at a glance. Didn't find it on my first round of ctrl+f through the page. What would help is better formatting, maybe a table of definitions/key terms or at least bullet points? Just something that makes it easy to absorb the gist at a glance, but still has all the content if someone is doing a serious read-through

**Comment by bhuvy2** [comment]
Added a reminder once we got to the conceptual part for ctrl-f. Would be nice to port this over to the glossary for quick formulas.
