### ISSUE TITLE
urandom versus random

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#77]
**Is your feature request related to a problem? Please describe.**
We should talk about urandom and random use cases

**Describe the solution you'd like**
A nuanced explanation of when to use random and urandom.

**Describe alternatives you've considered**
Nope

**Additional context**
Quick TLDR

```
Yup, so I confused the POSIX random system calls to the operating system specific devices --

http://pubs.opengroup.org/onlinepubs/9699919799.2018edition/

The abstraction is `/dev/random` and `/dev/urandom` being files. The whole idea behind a character device file abstraction is that you don't need to worry about the stream of data behind the device, you can treat it as a file that you can read and possibly write to.

Where the abstraction breaks down is `/dev/random` notably blocks when the entropy pool for the seeding engine is low where urandom will bootstrap itself leading to a file being easier to read. If we try to teach to the abstraction we are at a lose-lose scenario -- always using urandom will cause you to fail if you are writing a program that relies on randomness during bootup (an init.d runlevel) or if you need a true one time pad security -- think of a naive HTTPS implementation whose key exchange you want very secure.

Though some security experts will say to use `urandom` because otherwise an attacker will be able to cause your program to stutter, which could lead to all sorts of timing attacks that don't involve mathematically breaking through some cipher which we hadn't considered.

I'll throw my hands up and say this a more nuanced issue, and we don't expect everyone to be security experts by the end of the course. I'll make sure to include the subtlety in the book.
```

**Comment by aneeshdurg** [comment]
I'm not sure if I remember this correctly, but the entropy pool not being full is only possibly true during the first boot right? After which it's almost guaranteed that you have enough bits of entropy for /dev/random to not block?

**Comment by angrave** [comment]
No you can exhaust it easily if you are greedy
e.g. hexdump -C
Also some quiet systems with very little I/O have very little source entropy input.
So ultimately it's a design decision: 1) If there's insufficient entropy is it better to block than be guessable (=insecure for cryptographic concerns) 2. Only ask for the number of bits that you actually need.
3) Be aware that if you decide to use /dev/urandom as fallback for when /dev/random would block then a malicious actor may deliberately push you into this situation (e.g. by directly or indirectly eating up all available entropy from /dev/random). Decide if a denial of service is a better outcome than being insecure.
