### ISSUE TITLE
Dependencies /how to contribute? 

### ISSUE THREAD

**Issue by aneeshdurg** [illinois-cs241/coursebook#8]
Currently, for new contributors who may not have used latex before, it may be useful to document what steps should be taken to set up a development environment. We should determine what packages we used and what needs to be installed to contribute. 

As a temporary measure, we should at least point people to installing `texlive-full`.

Furthermore, we may want to consider adding a quick latex tutorial or linking to one, and also consider adding a style guide if some sort.

**Comment by bhuvy2** [comment]
Added to contributing.md .
