### ISSUE TITLE
Introc printf clarifications

### ISSUE THREAD

**Issue by aneeshdurg** [illinois-cs241/coursebook#92]
**Describe the bug**
Issues with correctness regarding printf facts

**Additional context**
This issue was brought up by @angrave as quoted below:

> Also
http://cs241.cs.illinois.edu/coursebook/Introc#common-c-functions
> 2) " printf includes an internal buffer so, to increase performance printf may not call write every time you call printf. " Hmmm. lease reword this - the internal buffer is part of the default stdout provided by the C-library, NOT inside printf specifically. (please check prior paragraph too)
> Also 3) "Another quirk of printf it is forced to call write on a newline character. "  that's not completely true e.g. if stdout has been redirected to a file. It's only true if the C-library detects stdout is going to a terminal-like device. Again not printf specifically. (edited)

**Comment by bhuvy2** [comment]
Has been resolved by PR
