### ISSUE TITLE
Consistent Styling Across all Code Blocks

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#95]
**Is your feature request related to a problem? Please describe.**
Right now our code blocks aren't styled the same (spaces vs tabs, brackets etc).

**Describe the solution you'd like**
We should manually (or with a script) one-shot all of the code blocks and format them.
Then on PRs, we'll review the style.
That being said, we should have an agreed upon style first.

**Describe alternatives you've considered**
The alternating styles of blocks look a little odd now, but can be ignored if there are bigger fish to fry.

**Additional context**
N/A

**Comment by aneeshdurg** [comment]
Would moving to luatex allow us to define/use macros that format code snippets?

**Comment by bhuvy2** [comment]
Yes, but until we have a pandoc layer, the markdown and html versions will be unformatted.
